name: bayes_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.12
  - numpy
  - jax
  - flax
  - optax
  - tqdm
  - numba
  - pandas
  - scikit-learn
  - matplotlib
  - ipython
  - ipykernel
  - pip:
    - ucimlrepo
